export { default as Home } from "./Home";
export { default as Features } from "./Features";
export { default as Pricing } from "./Pricing";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Privacy } from "./Privacy";
export { default as Terms } from "./Terms";
export { default as ModulePage } from "./ModulePage";
export { default as ModuleDocs } from "./ModuleDocs";
